### ISSUE TITLE
continuous integration to ease testing new PR

### ISSUE THREAD

**Issue by sammyne** [universal-secure-computing-community/crates-sgx#6]
It would be better if there is a CI validating every PR before manual reviewing.

I'd  like to help with that with CircleCI, and will propose a PR for that later.

If ok, assign this issue a enhancement label, please~

**Comment by mssun** [comment]
Yes, though we can only run in simulation mode with public CI.

BTW, how about GitHub Action? I guess it will integrated with GitHub well.

**Comment by sammyne** [comment]
Ok, I'll give Github Action a shot
